---
image_pull_secrets:
- DOCKER_REGISTRY_AUTHENTICATION_JSON
kind: pipeline
name: CI pipeline
steps:
- commands:
  - restore-cache
  environment:
    CACHE_EXTRA_DIRS: /root/.cargo,/root/.npm,/root/.rustup,.blaze/cache,.blaze/repositories,.blaze/rust
    CACHE_KEY: blaze-ci-${DRONE_BRANCH}
    CACHE_STORAGE: /var/lib/cache
  failure: ignore
  image: registry.rnzaou.me/ci:latest
  name: restore cache
  pull: always
  volumes:
  - name: cache
    path: /var/lib/cache
  when:
    branch:
      exclude:
      - master
- commands:
  - blaze run --target lint --all
  image: registry.rnzaou.me/ci:latest
  name: check
  pull: always
- commands:
  - blaze run cli:build-release
  - blaze run --projects website,downloads --target build
  image: registry.rnzaou.me/ci:latest
  name: build
  pull: always
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
- commands:
  - blaze run tests:run-release
  image: registry.rnzaou.me/ci:latest
  name: test
  pull: always
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
- commands:
  - create-cache
  environment:
    CACHE_EXTRA_DIRS: /root/.cargo,/root/.npm,/root/.rustup,.blaze/cache,.blaze/repositories,.blaze/rust
    CACHE_KEY: blaze-ci-${DRONE_BRANCH}
    CACHE_STORAGE: /var/lib/cache
  failure: ignore
  image: registry.rnzaou.me/ci:latest
  name: create cache
  pull: always
  volumes:
  - name: cache
    path: /var/lib/cache
  when:
    branch:
      exclude:
      - master
trigger:
  event:
  - push
  - custom
type: docker
volumes:
- host:
    path: /var/lib/cache
  name: cache
- host:
    path: /run/user/1002/docker.sock
  name: docker-socket
---
image_pull_secrets:
- DOCKER_REGISTRY_AUTHENTICATION_JSON
kind: pipeline
name: Publish pipeline
steps:
- commands:
  - blaze run --parallelism None --all --target publish
  environment:
    CARGO_TOKEN:
      from_secret: CARGO_TOKEN
    DOCKER_REGISTRY_PASSWORD:
      from_secret: DOCKER_REGISTRY_PASSWORD
    DOCKER_REGISTRY_USERNAME:
      from_secret: DOCKER_REGISTRY_USERNAME
    NPM_TOKEN:
      from_secret: NPM_TOKEN
  image: registry.rnzaou.me/ci:latest
  name: publish packages
  pull: always
  volumes:
  - name: docker-socket
    path: /var/run/docker.sock
- commands:
  - blaze run ci:push-release
  image: registry.rnzaou.me/ci:latest
  name: push release changes
  pull: always
  volumes:
  - name: ssh
    path: /root/.ssh
- commands:
  - blaze run --parallelism None cli:deploy
  environment:
    DOCKER_REGISTRY_PASSWORD:
      from_secret: DOCKER_REGISTRY_PASSWORD
    DOCKER_REGISTRY_USERNAME:
      from_secret: DOCKER_REGISTRY_USERNAME
  image: registry.rnzaou.me/ci:latest
  name: deploy binaries
  pull: always
  volumes:
  - name: builds
    path: /var/lib/blaze/builds
  - name: docker-socket
    path: /var/run/docker.sock
trigger:
  event:
  - promote
type: docker
volumes:
- host:
    path: /var/lib/drone/.ssh
  name: ssh
- host:
    path: /var/lib/blaze/builds
  name: builds
- host:
    path: /run/user/1002/docker.sock
  name: docker-socket
---
kind: signature
hmac: 850551cd6986ff349bbd41a74140b11b9c7832fa10e94fd5485d874baf8668b9

...
