[package]
name = "blaze-devkit"
description = "Rust devkit for the Blaze build system."
repository = "https://github.com/rnza0u/main.git"
homepage = "https://blaze-monorepo.dev"
license = "MIT"
version = "0.2.11"
edition = "2021"

[dependencies]
blaze-common = { path = "../../common", version = "0.2.11" }
hash-value = { version = "1.0" }
url = "2.3.1"

[lib]